### ISSUE TITLE
tooltip issue on href feild

### ISSUE THREAD

**Issue by masterdaak** [skyout/tips.js#1]
Hello, hope you are well no doubt its a very magical plugin but i have some issue. 
I have added this in my href. 
Example : 
 href="#"  target="_blank" data-tooltip="Facebook" data-tooltip-direction="top" class="hover"

tooltip is working like a charm but i think my a tag is disable due to tooltip its not more clickable . Please help me on this issue. 

Thanks.

**Comment by skyout** [comment]
As of 1.0.9, hover/focus/blur does not prevent default actions of the elements.
